In [1]:
import numpy as np

## Write a function so that the columns of the output matrix are powers of the input vector.

In [3]:
def gen_vander_matrix(vec, n, increasing=False):    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in vec for i in range(n)]).reshape(vec.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in vec for i in range(n)]).reshape(vec.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

vec = np.array([1,2,3,4,5])
col = 4
op_matx_dec_order = gen_vander_matrix(vec,col,False)
op_matx_inc_order = gen_vander_matrix(vec,col,True)

print("The input array is:",vec,"\n")
print("Number of columns in output matrix should be:",col,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



## Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def moving_avg(lst, N):
    avgMovingList = []
    for i in range(0, len(lst)-N):
        tempList = list(lst[k] for k in range(i, i+N))
        avgMovingList.append(round((sum(tempList)/N),2))
    print("--------- OUTPUT ----------")
    return avgMovingList
print(moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3))

--------- OUTPUT ----------
[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33]
